name: Deploy to Firebase Hosting
'on':
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    - name: Write Firebase service account to file
      run: echo "$FIREBASE_SERVICE_ACCOUNT" > "${{ github.workspace }}/firebase.json"
    - name: Deploy to Firebase
      run: firebase deploy --only hosting --project open-anonymous --token $(firebase
        login:ci --no-localhost)
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
